"""Constant-time bearer authentication for the K'ab ingest receiver.

Every media endpoint requires `Authorization: Bearer <token>`. The token is
generated by the cert CLI (48 bytes of CSPRNG entropy), lives only in a
runtime file outside version control, and is never logged: the comparison
runs over SHA-256 digests of both sides so the comparison is constant-time
regardless of length mismatch, and no code path ever writes the presented
or configured token into logs, error messages, or API responses.
"""

from __future__ import annotations

import hashlib
import hmac


def constant_time_token_match(provided: str | None, expected: str | None) -> bool:
    if not provided or not expected:
        return False
    provided_digest = hashlib.sha256(provided.encode("utf-8")).digest()
    expected_digest = hashlib.sha256(expected.encode("utf-8")).digest()
    return hmac.compare_digest(provided_digest, expected_digest)


def extract_bearer_token(header_value: str | None) -> str | None:
    if not header_value:
        return None
    parts = header_value.strip().split(None, 1)
    if len(parts) != 2 or parts[0].lower() != "bearer":
        return None
    token = parts[1].strip()
    return token or None
