"""Typed configuration for the K'ab ingest receiver/worker.

Separate from `transcript_pipeline.settings.Settings`: the ingest receiver is
its own process with its own trust boundary, and its defaults must be the
strictest possible posture (disabled, no host, TLS credentials unset).

Environment variables (all prefixed `KAB_INGEST_`):
    KAB_INGEST_ENABLED        default false — receiver never starts unless set
    KAB_INGEST_HOST           unset by default — required when enabled, must
                              pass the bind policy (see bind.py)
    KAB_INGEST_PORT           default 5443
    KAB_INGEST_TOKEN          unset by default — bearer token, generated by
                              the cert CLI, never committed
    KAB_INGEST_CERT           unset by default — TLS certificate PEM path
    KAB_INGEST_KEY            unset by default — TLS private key PEM path
    KAB_INGEST_MAX_CHUNK_MB   default 8 — per-chunk upload cap
    KAB_INGEST_MAX_SESSION_GB default 50 — cumulative per-session cap
    KAB_INGEST_ROOT           default DATA_ROOT/kab-inbox — storage root
"""

from __future__ import annotations

import os
from dataclasses import dataclass
from pathlib import Path

from transcript_pipeline.config import DATA_ROOT
from transcript_pipeline.errors import ConfigurationError
from transcript_pipeline.kab_ingest.bind import validate_bind_host

DEFAULT_PORT = 5443
DEFAULT_MAX_CHUNK_MB = 8
DEFAULT_MAX_SESSION_GB = 50


def _bool_env(name: str, default: bool) -> bool:
    val = os.getenv(name)
    if val is None:
        return default
    return val.strip().lower() not in {"0", "false", "no", ""}


def _int_env(name: str, default: int) -> int:
    raw = os.getenv(name)
    if raw is None or not raw.strip():
        return default
    try:
        return int(raw.strip())
    except ValueError as exc:
        raise ConfigurationError(f"{name} must be an integer: {raw!r}") from exc


@dataclass(frozen=True)
class KabIngestSettings:
    enabled: bool = False
    host: str | None = None
    port: int = DEFAULT_PORT
    token: str | None = None
    cert_file: Path | None = None
    key_file: Path | None = None
    max_chunk_mb: int = DEFAULT_MAX_CHUNK_MB
    max_session_gb: int = DEFAULT_MAX_SESSION_GB
    root: Path | None = None

    @classmethod
    def from_env(cls) -> KabIngestSettings:
        host_raw = os.getenv("KAB_INGEST_HOST")
        host = None
        if host_raw is not None and host_raw.strip():
            host = validate_bind_host(host_raw)
        root_raw = os.getenv("KAB_INGEST_ROOT")
        root: Path | None = None
        if root_raw is not None and root_raw.strip():
            root = _resolve_root(Path(root_raw.strip()))
        return cls(
            enabled=_bool_env("KAB_INGEST_ENABLED", False),
            host=host,
            port=_int_env("KAB_INGEST_PORT", DEFAULT_PORT),
            token=os.getenv("KAB_INGEST_TOKEN") or None,
            cert_file=_optional_path("KAB_INGEST_CERT"),
            key_file=_optional_path("KAB_INGEST_KEY"),
            max_chunk_mb=_int_env("KAB_INGEST_MAX_CHUNK_MB", DEFAULT_MAX_CHUNK_MB),
            max_session_gb=_int_env("KAB_INGEST_MAX_SESSION_GB", DEFAULT_MAX_SESSION_GB),
            root=root,
        )

    @property
    def max_chunk_bytes(self) -> int:
        return self.max_chunk_mb * 1024 * 1024

    @property
    def max_session_bytes(self) -> int:
        return self.max_session_gb * 1024 * 1024 * 1024

    def storage_root(self) -> Path:
        if self.root is not None:
            return self.root
        return _resolve_root(Path("kab-inbox"))

    def validate_for_server(self) -> None:
        """Full startup gate: refuses anything that would weaken the posture."""
        if not self.enabled:
            raise ConfigurationError(
                "KAB_INGEST_ENABLED is false — the K'ab ingest receiver never starts implicitly."
            )
        if self.host is None:
            raise ConfigurationError("KAB_INGEST_HOST is required when the receiver is enabled.")
        if self.token is None or not self.token.strip():
            raise ConfigurationError("KAB_INGEST_TOKEN is required when the receiver is enabled.")
        if self.cert_file is None or self.key_file is None:
            raise ConfigurationError(
                "KAB_INGEST_CERT and KAB_INGEST_KEY are required — plain HTTP is never accepted."
            )
        if not (1024 <= self.port <= 65535):
            raise ConfigurationError(f"KAB_INGEST_PORT out of range (1024-65535): {self.port}")
        if self.max_chunk_mb <= 0:
            raise ConfigurationError(f"KAB_INGEST_MAX_CHUNK_MB must be positive: {self.max_chunk_mb}")
        if self.max_session_gb <= 0:
            raise ConfigurationError(f"KAB_INGEST_MAX_SESSION_GB must be positive: {self.max_session_gb}")
        if self.max_session_bytes < self.max_chunk_bytes:
            raise ConfigurationError(
                "KAB_INGEST_MAX_SESSION_GB must allow at least one max-size chunk."
            )


def _optional_path(name: str) -> Path | None:
    raw = os.getenv(name)
    if raw is None or not raw.strip():
        return None
    return Path(raw.strip())


def _resolve_root(raw: Path) -> Path:
    from transcript_pipeline.config import DATA_ROOT

    if raw.is_absolute():
        return raw.resolve(strict=False)
    return (DATA_ROOT / raw).resolve(strict=False)
